### ISSUE TITLE
Is the :key key used in the redis_store config?

### ISSUE THREAD

**Issue by brendon** [redis-store/redis-rails#86]
Hi there, I was wondering if the `key:` mentioned in the example config below is actually used? I did some inspection of the keys stored in redis with this config and the key isn't mentioned anywhere. The namespace is 'session' but that's about it.

I omitted it in my config in the end but just wanted to check to see if you knew what it's used for.

```
MyApplication::Application.config.session_store :redis_store, {
  servers: [
    {
      host: "localhost",
      port: 6379,
      db: 0,
      password: "mysecret",
      namespace: "session"
    },
  ],
  expire_after: 90.minutes,
  key: "_#{Rails.application.class.parent_name.downcase}_session"
}
```

**Comment by tubbo** [comment]
It's used in the core interface of all this session management stuff, [Rack::Session::Abstract::ID](https://github.com/rack/rack/blob/master/lib/rack/session/abstract/id.rb#L222). This is the base class of [Rack::Session::Redis](https://github.com/redis-store/redis-rack/blob/master/lib/rack/session/redis.rb#L8), which itself is the base class of [ActionDispatch::Session::RedisStore](https://github.com/redis-store/redis-actionpack/blob/master/lib/action_dispatch/middleware/session/redis_store.rb), which is the object you're invoking when configuring your session store to be `:redis_store`.

By virtue of that fun little inheritance chain, we gain access to [the key method](https://github.com/redis-store/redis-actionpack/blob/master/lib/action_dispatch/middleware/session/redis_store.rb#L26) within the Redis session store, so that's where it's being used.

You're right, there isn't really clear documentation on how this is working. Since this is a common interface shared by all Rails session store implementations, I would say the best place for documentation on this feature is the Rails guides. There is _some_ information on api.rubyonrails.org, but it's really just explaining that the option exists and how to use it, not _why_ it exists.

**Comment by brendon** [comment]
Thanks @tubbo :) Yes I started to dig into the code but then found the redis-rails gem mostly empty and hoped (not in vain) that you'd have a better answer than one I could dig up :) Thanks for obliging :D

So the `:key` option allows us to rename the session cookie key which by default is `_session_id`.

Thanks again! :D
