### ISSUE TITLE
Setting expiry date for namespaced cache_store

### ISSUE THREAD

**Issue by tomily1** [redis-store/redis-rails#87]
I am not sure if the issue should be raised here but when using the `redis-namespace` gem, using this particular config 
`config.cache_store = :redis_store, "redis://localhost:6379/0/cache", { expires_in: 1.week }` will not expire the store unless the namespace is included in the config. Perhaps this might be included in the README.

**Comment by tubbo** [comment]
That's correct, the `redis-namespace` gem isn't used by `redis-store`. [We have our own mixin to deal with namespaces](https://github.com/redis-store/redis-store/blob/master/lib/redis/store/namespace.rb) because `Redis::Store` already subclasses `Redis`.

[You can pass your own Redis client](https://github.com/redis-store/redis-rack/blob/master/lib/redis/rack/connection.rb#L6) as an object into `config.cache_store` like so, but I'm not sure if it will work correctly, since we're really testing against an instance of `Redis::Store`, not `Redis::Namespace`.

```ruby
config.cache_store = :redis_store, "redis://localhost:6379/0/cache", { expires_in: 1.week, redis_store: YOUR_EXISTING_REDIS_NAMESPACE_INSTANCE }
```

All that aside, I think it's just easier to pass the `:namespace` as a config option into `config.cache_store`, and not use the additional redis-namespace gem.

**Comment by tomily1** [comment]
ahhh, yes!. Thank you for clarifying
