### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by andrewmcodes** [redis-store/redis-rails#95]
Are there any plans to support rails 6? I noticed you have rails constrained to versions below 6.

**Comment by tubbo** [comment]
@andrewmcodes there's no need to use `redis-rails` if you're using Rails 6, since it ships with its own cache store, `:redis_cache_store`. if you want to use the session management capabilities, you can just use `gem 'redis-actionpack'`. this gem was made to make it a bit easier to include redis-store into the app, as previously all these various redis adapters were contained in one redis-store gem.

**Comment by andrewmcodes** [comment]
Ah I didn’t know that. Thanks for your informative reply!
